const express=require("express")
const {authenticateUser,authorizeUser}=require('../Middlewares/auth')
const { createUser, updateProfile, updatePassword, myDetails,  loginUser,getAllUsers,getUser,deleteUser,logoutUser, showWeather} = require("../controllers/userControllers")
const router=express.Router()
router.route('/User/createUser').post(createUser)
router.route('/User/showWeather').post(authenticateUser,showWeather)
router.route('/User/getUser/:id').get(authenticateUser,authorizeUser('admin'),getUser)
router.route('/User/getAllUsers').get(authenticateUser,authorizeUser('admin'),getAllUsers)
router.route('/User/loginUser').post(loginUser)
router.route('/User/updatePassword').put(authenticateUser,updatePassword)
router.route('/User/updateProfile').put(authenticateUser,updateProfile)
router.route('/User/logoutUser').get(logoutUser)
router.route('/User/deleteUser/:id').delete(authenticateUser,authorizeUser('admin'),deleteUser)
router.route('/User/myDetails').get(authenticateUser,myDetails)
module.exports=router
